[
  {
    nombre: 'Solange Estudiante',
    email: 'solange@email.com',
    dni: '63058133022',
    activo: true,
    rol: 'estudiante',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    nombre: 'Igor Estudiante',
    email: 'igor@email.com',
    dni: '99018205028',
    activo: true,
    rol: 'estudiante',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    nombre: 'Aline Estudiante',
    email: 'aline@email.com',
    dni: '92797497066',
    activo: true,
    rol: 'estudiante',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    nombre: 'Fernando Estudiante',
    email: 'fernando@email.com',
    dni: '17195730000',
    activo: true,
    rol: 'estudiante',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    nombre: 'Ricardo Docente',
    email: 'ricardo@email.com',
    dni: '06946507061',
    activo: true,
    rol: 'docente',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    nombre: 'Dine Docente',
    email: 'dine@email.com',
    dni: '80941142078',
    activo: true,
    rol: 'docente',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    nombre: 'Leonardo Estudiante',
    email: 'leonardo@email.com',
    dni: '13804059',
    activo: true,
    rol: 'estudiante',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    nombre: 'Juliana Docente',
    email: 'juliana@email.com',
    dni: '21183784',
    activo: true,
    rol: 'docente',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    nombre: 'Rosa Docente',
    email: 'rosa@email.com',
    dni: '8001879',
    activo: true,
    rol: 'docente',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
